name: Travis CI
on: [push]
language: node_js
before_install: 
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
install: yarn install && yarn run lint
cache: yarn